export const PRELOAD_API_DOMAIN_TARGET = 'window.helm.<domain>';

export const PRELOAD_API_COMPATIBILITY_POLICY = {
  electronBoundary: 'contextBridge remains the only window exposure boundary.',
  legacyFacade: 'window.gamepadCli stays as a compatibility facade while renderer callers migrate to domain clients.',
  domainOwnership: 'Every legacy preload method must be assigned to exactly one target window.helm domain.',
} as const;

export const PRELOAD_API_DOMAINS = {
  app: [
    'appGetVersion',
    'appStartupReady',
  ],
  sessions: [
    'sessionSetActive',
    'sessionGetActive',
    'sessionRemove',
    'sessionClose',
    'sessionSnapOut',
    'sessionSnapBack',
    'sessionRename',
    'sessionSetState',
  ],
  terminal: [
    'ptySpawn',
    'ptyWrite',
    'ptyScrollInput',
    'ptyResize',
    'ptyMarkSwitching',
    'ptyKill',
  ],
  delivery: [
    'textDeliverResponse',
    'textDeliverReady',
    'pipelineEnqueue',
    'pipelineDequeue',
    'pipelineGetQueue',
    'pipelineGetPosition',
  ],
  config: [
    'configGetAll',
    'configGetBindings',
    'configGetCliTypes',
    'configGetSequences',
    'configGetChipbarActions',
    'configSetChipbarActions',
    'configSetSequenceGroup',
    'configRemoveSequenceGroup',
    'configSetBinding',
    'configRemoveBinding',
    'configCopyCliBindings',
    'configGetHapticFeedback',
    'configSetHapticFeedback',
    'configGetNotifications',
    'configSetNotifications',
    'configGetMcpConfig',
    'configSetMcpConfig',
    'configGenerateMcpToken',
    'configGetEscProtectionEnabled',
    'configSetEscProtectionEnabled',
    'configGetSortPrefs',
    'configSetSortPrefs',
    'configGetPlanFilters',
    'configSetPlanFilters',
    'configGetSessionGroupPrefs',
    'configSetSessionGroupPrefs',
    'configRemoveBookmarkedDir',
    'configGetSpawnCommand',
    'configGetCliTypeEnv',
    'configGetDpadConfig',
    'configGetStickConfig',
    'configGetCollapsePrefs',
    'configSetCollapsePrefs',
    'configGetEditorPrefs',
    'configSetEditorPrefs',
    'configGetWorkingDirs',
    'configAddWorkingDir',
    'configUpdateWorkingDir',
    'configRemoveWorkingDir',
    'configReorderWorkingDir',
  ],
  tools: [
    'toolsGetAll',
    'toolsAddCliType',
    'toolsUpdateCliType',
    'toolsRemoveCliType',
    'toolsReorderCliType',
  ],
  projects: [
    'projectList',
    'projectGet',
    'projectCreate',
    'projectUpdate',
    'projectDelete',
    'projectAddDir',
    'projectRemoveDir',
  ],
  skills: [
    'skillList',
    'skillGet',
    'skillCreate',
    'skillUpdate',
    'skillDelete',
    'skillClone',
  ],
  plans: [
    'planList',
    'planCreate',
    'planUpdate',
    'planDelete',
    'planClearCompleted',
    'planAddDep',
    'planRemoveDep',
    'planApply',
    'planComplete',
    'planReopen',
    'planSetState',
    'planStartableForDir',
    'planDoingForSession',
    'planGetAllDoingForDir',
    'planDeps',
    'planGetItem',
    'planSequenceList',
    'planSequenceCreate',
    'planSequenceUpdate',
    'planSequenceDelete',
    'planSequenceAssign',
    'planBulkAssignSequence',
    'planSequenceDeleteWithPlans',
    'planPopOut',
  ],
  contexts: [
    'planContextList',
    'planContextCreate',
    'planContextUpdate',
    'planContextDelete',
    'planContextGet',
    'planContextAppend',
    'planContextSetPosition',
    'planContextBind',
    'planContextUnbind',
  ],
  attachments: [
    'planAttachmentList',
    'planAttachmentHasAny',
    'planAttachmentAddFile',
    'planAttachmentDelete',
    'planAttachmentOpen',
  ],
  backups: [
    'planListBackups',
    'planGetBackupSummary',
    'planRestoreBackup',
    'planDeleteBackup',
    'planCreateBackupNow',
    'planGetBackupConfig',
    'planSetBackupConfig',
    'planDeleteAllBackups',
  ],
  incoming: [
    'planIncomingList',
    'planIncomingDelete',
    'planIncomingOpen',
    'planExportItem',
    'planExportDirectory',
    'planReadFile',
    'planWriteFile',
  ],
  drafts: [
    'draftCreate',
    'draftUpdate',
    'draftDelete',
    'draftList',
    'draftCount',
    'editorGetHistory',
    'editorSetHistory',
  ],
  scheduler: [
    'scheduledTaskCreate',
    'scheduledTaskList',
    'scheduledTaskGet',
    'scheduledTaskUpdate',
    'scheduledTaskCancel',
    'scheduledTaskDelete',
  ],
  patterns: [
    'toolsGetPatterns',
    'toolsAddPattern',
    'toolsUpdatePattern',
    'toolsRemovePattern',
    'patternCancelSchedule',
  ],
  telegram: [
    'telegramGetConfig',
    'telegramSetConfig',
    'telegramStart',
    'telegramStop',
    'telegramIsRunning',
    'telegramTestConnection',
  ],
  keyboard: [
    'keyboardKeyTap',
    'keyboardSendKeyCombo',
    'keyboardComboDown',
    'keyboardComboUp',
    'keyboardTypeString',
  ],
  dialog: [
    'dialogOpenFolder',
    'dialogShowOpenFile',
    'dialogShowSaveFile',
    'editorOpenExternal',
    'writeTempContent',
    'deleteTemp',
  ],
  system: [
    'systemOpenLogsFolder',
  ],
  events: [
    'onPtyData',
    'onPtyExit',
    'onPtyQuestionDetected',
    'onPtyQuestionCleared',
    'onPtyActivityChange',
    'onTextDeliverRequest',
    'onPtyHandoff',
    'onNotificationClick',
    'onLlmNotify',
    'onSessionSpawned',
    'onSessionUpdated',
    'onSnapOut',
    'onSnapBack',
    'onPlanBackupCreated',
    'onPlanBackupDeleted',
    'onPlanBackupRestored',
    'onPlanBackupConfigChanged',
    'onPlanChanged',
    'onPlanIncomingImported',
    'onPlanIncomingError',
    'onPlanIncomingErrorCleared',
    'onPatternScheduleCreated',
    'onPatternScheduleFired',
    'onPatternScheduleCancelled',
    'onScheduledTaskChanged',
  ],
} as const;

export type PreloadApiDomain = keyof typeof PRELOAD_API_DOMAINS;

export function getPreloadApiDomain(methodName: string): PreloadApiDomain | undefined {
  return (Object.entries(PRELOAD_API_DOMAINS) as Array<[PreloadApiDomain, readonly string[]]>)
    .find(([, methods]) => methods.includes(methodName))?.[0];
}
