name: Default
cliTypes:
  claude-code:
    Y:
      action: keyboard
      keys:
        - /
        - c
        - o
        - m
        - p
        - a
        - c
        - t
    RightTrigger:
      action: keyboard
      keys:
        - Insert
      hold: true
    LeftTrigger:
      action: keyboard
      keys:
        - Enter
    A:
      action: keyboard
      keys:
        - Insert
      hold: true
  copilot-cli:
    A:
      action: keyboard
      keys:
        - Clear
    B:
      action: keyboard
      keys:
        - Escape
    X:
      action: keyboard
      keys:
        - "?"
        - Enter
  generic-terminal:
    A:
      action: keyboard
      keys:
        - Clear
    B:
      action: keyboard
      keys:
        - Ctrl
        - c
    LeftBumper:
      action: keyboard
      keys:
        - as asd
  python:
    A:
      action: keyboard
      keys:
        - Enter
global:
  Xbox:
    action: hub-focus
  Back:
    action: profile-switch
    direction: previous
  Start:
    action: profile-switch
    direction: next
sticks:
  left:
    mode: cursor
    deadzone: 0.25
    repeatRate: 100
  right:
    mode: scroll
    deadzone: 0.25
    repeatRate: 150
