plans:
  X:\coding\Vitido:
    dirPath: X:\coding\Vitido
    items:
      - id: ee4ecb5c-bb7b-4c04-941f-af39ff2157b8
        dirPath: X:\coding\Vitido
        title: potato
        description: ""
        status: done
        createdAt: 1776264719619
        updatedAt: 1776264861069
        sessionId: pty-claude-code-1776264715120
      - id: 52d58817-42c0-40e8-81bc-42cc3a208719
        dirPath: X:\coding\Vitido
        title: blah blah
        description: something something
        status: done
        createdAt: 1776264722519
        updatedAt: 1776352521847
        sessionId: pty-claude-code-1776264715120
      - id: d108078e-dd33-46a3-9af4-ef40dba7dc24
        dirPath: X:\coding\Vitido
        title: Thingy
        description: thing thing thing
        status: done
        createdAt: 1776347716030
        updatedAt: 1776352609388
        sessionId: pty-claude-code-1776347701267
      - id: 0da832a2-398e-44b8-8248-0c5995f90fc9
        dirPath: X:\coding\Vitido
        title: horse shit
        description: a sdf akjsd;lkfj asldkfj alskd sa
        status: pending
        createdAt: 1776347727814
        updatedAt: 1776347740179
      - id: 0a388eed-7acd-4ce3-b870-a4b9e82645f5
        dirPath: X:\coding\Vitido
        title: sigmaboi
        description: "67 67 67 67 67 67 67 67 67 67 "
        status: pending
        createdAt: 1776347765677
        updatedAt: 1776347781941
      - id: 5a8037e4-7624-459f-bd74-47a3672b49b7
        dirPath: X:\coding\Vitido
        title: blhjalbaj lakbjadfba
        description: |-
          sadfasdf asdf asdf 
           sad
          f 
          asdf
           as
          df 
          asd
          f a
          sdf
           as
          f 
          asdf s f
        status: blocked
        createdAt: 1776347800566
        updatedAt: 1776466241854
        sessionId: pty-claude-code-1776466200952
        stateInfo: googoo
      - id: d00d45fe-5fd9-4e53-bbe6-d9a7811981fd
        dirPath: X:\coding\Vitido
        title: New Plan
        description: ""
        status: pending
        createdAt: 1776351502504
        updatedAt: 1776351545033
      - id: 3ea0f183-0622-4fb0-a0b8-1b1bcf3ef34f
        dirPath: X:\coding\Vitido
        title: XYZ
        description: ""
        status: doing
        createdAt: 1776352529295
        updatedAt: 1776466279106
        sessionId: pty-claude-code-1776466269856
      - id: a33b373a-bf0b-4f9c-a392-4d082e387338
        dirPath: X:\coding\Vitido
        title: New Plan
        description: ""
        status: startable
        createdAt: 1776460460315
        updatedAt: 1776460460315
    dependencies:
      - fromId: 52d58817-42c0-40e8-81bc-42cc3a208719
        toId: ee4ecb5c-bb7b-4c04-941f-af39ff2157b8
      - fromId: 52d58817-42c0-40e8-81bc-42cc3a208719
        toId: d108078e-dd33-46a3-9af4-ef40dba7dc24
      - fromId: d108078e-dd33-46a3-9af4-ef40dba7dc24
        toId: 0da832a2-398e-44b8-8248-0c5995f90fc9
      - fromId: 52d58817-42c0-40e8-81bc-42cc3a208719
        toId: 0a388eed-7acd-4ce3-b870-a4b9e82645f5
      - fromId: d108078e-dd33-46a3-9af4-ef40dba7dc24
        toId: 5a8037e4-7624-459f-bd74-47a3672b49b7
      - fromId: 0a388eed-7acd-4ce3-b870-a4b9e82645f5
        toId: d00d45fe-5fd9-4e53-bbe6-d9a7811981fd
      - fromId: 52d58817-42c0-40e8-81bc-42cc3a208719
        toId: 3ea0f183-0622-4fb0-a0b8-1b1bcf3ef34f
      - fromId: 3ea0f183-0622-4fb0-a0b8-1b1bcf3ef34f
        toId: 0a388eed-7acd-4ce3-b870-a4b9e82645f5
      - fromId: 3ea0f183-0622-4fb0-a0b8-1b1bcf3ef34f
        toId: 0da832a2-398e-44b8-8248-0c5995f90fc9
  X:\coding\stillhere:
    dirPath: X:\coding\stillhere
    items:
      - id: 1bd469b5-5c14-4c45-93f8-48ec5be2645f
        dirPath: X:\coding\stillhere
        title: New Plan
        description: ""
        status: done
        createdAt: 1776264927432
        updatedAt: 1776264946034
        sessionId: pty-claude-code-1776264923187
      - id: ae753b1c-e8e7-4998-afbf-ee51c753527e
        dirPath: X:\coding\stillhere
        title: New Plan
        description: ""
        status: done
        createdAt: 1776264929192
        updatedAt: 1776352214624
        sessionId: pty-claude-code-1776264923187
      - id: 16fb4901-1293-4997-b53a-d63a456d245f
        dirPath: X:\coding\stillhere
        title: egg
        description: "golakf ajsd lfk jasdlkfj askdlfj asdf "
        status: doing
        createdAt: 1776265934324
        updatedAt: 1776346314991
        sessionId: pty-claude-code-1776265845829
      - id: aafd7c24-4652-443f-8485-ccdfba8e95fe
        dirPath: X:\coding\stillhere
        title: carrot
        description: ""
        status: pending
        createdAt: 1776265960369
        updatedAt: 1776265966178
      - id: 18c5fe49-5345-452f-9f8a-838b39ca60d1
        dirPath: X:\coding\stillhere
        title: Poopy
        description: thinghnt
        status: startable
        createdAt: 1776351406273
        updatedAt: 1776352487717
      - id: 9d69a188-cc2a-4804-94da-e8a49cfca80c
        dirPath: X:\coding\stillhere
        title: New Plan
        description: ""
        status: pending
        createdAt: 1776352194227
        updatedAt: 1776352194227
      - id: d1694b01-9393-4ccc-97a6-7bf2ec0f8655
        dirPath: X:\coding\stillhere
        title: New Plan
        description: ""
        status: startable
        createdAt: 1776352194451
        updatedAt: 1776352194451
      - id: 08b8db1f-2039-4ce0-844a-f7ec2039ee39
        dirPath: X:\coding\stillhere
        title: New Plan
        description: ""
        status: pending
        createdAt: 1776352194843
        updatedAt: 1776352194843
      - id: 387a7cf6-6ee8-427c-bee8-9eeb0ee46255
        dirPath: X:\coding\stillhere
        title: New Plan
        description: ""
        status: startable
        createdAt: 1776491083337
        updatedAt: 1776491083337
      - id: 1e9d5012-854e-4c55-948f-fd962d352a69
        dirPath: X:\coding\stillhere
        title: New Plan
        description: ""
        status: startable
        createdAt: 1776491085281
        updatedAt: 1776491085281
    dependencies:
      - fromId: 18c5fe49-5345-452f-9f8a-838b39ca60d1
        toId: 16fb4901-1293-4997-b53a-d63a456d245f
      - fromId: 16fb4901-1293-4997-b53a-d63a456d245f
        toId: 9d69a188-cc2a-4804-94da-e8a49cfca80c
      - fromId: 9d69a188-cc2a-4804-94da-e8a49cfca80c
        toId: aafd7c24-4652-443f-8485-ccdfba8e95fe
      - fromId: aafd7c24-4652-443f-8485-ccdfba8e95fe
        toId: 08b8db1f-2039-4ce0-844a-f7ec2039ee39
  O:\OneDrive\Personal\Agnes\Documents\Job Applications and Performance Reviews\2026 Job Applications:
    dirPath: O:\OneDrive\Personal\Agnes\Documents\Job Applications and Performance
      Reviews\2026 Job Applications
    items:
      - id: 2884fa72-0008-420a-b44b-0c393a70734a
        dirPath: O:\OneDrive\Personal\Agnes\Documents\Job Applications and Performance
          Reviews\2026 Job Applications
        title: New Plan
        description: ""
        status: startable
        createdAt: 1776347011201
        updatedAt: 1776347011201
      - id: f0a9e57e-756c-45cd-b7cb-ded10de9a0f1
        dirPath: O:\OneDrive\Personal\Agnes\Documents\Job Applications and Performance
          Reviews\2026 Job Applications
        title: New Plan
        description: ""
        status: pending
        createdAt: 1776347013525
        updatedAt: 1776347013525
      - id: bf59301d-887c-42ad-97c1-746a7fb8bf2f
        dirPath: O:\OneDrive\Personal\Agnes\Documents\Job Applications and Performance
          Reviews\2026 Job Applications
        title: New Plan
        description: ""
        status: pending
        createdAt: 1776347063389
        updatedAt: 1776347063389
      - id: 1114ad29-7e4e-44d1-a813-88c7b3bc2dae
        dirPath: O:\OneDrive\Personal\Agnes\Documents\Job Applications and Performance
          Reviews\2026 Job Applications
        title: New Plan
        description: ""
        status: pending
        createdAt: 1776347148177
        updatedAt: 1776347148177
      - id: 75c880dd-c3cd-40a7-a7df-8a58324f6496
        dirPath: O:\OneDrive\Personal\Agnes\Documents\Job Applications and Performance
          Reviews\2026 Job Applications
        title: New Plan
        description: ""
        status: pending
        createdAt: 1776347154155
        updatedAt: 1776347154155
      - id: 61a94fb6-1ff0-47ec-a600-5d8a8fcf25f1
        dirPath: O:\OneDrive\Personal\Agnes\Documents\Job Applications and Performance
          Reviews\2026 Job Applications
        title: New Plan
        description: ""
        status: pending
        createdAt: 1776347163270
        updatedAt: 1776347163270
    dependencies:
      - fromId: 2884fa72-0008-420a-b44b-0c393a70734a
        toId: bf59301d-887c-42ad-97c1-746a7fb8bf2f
      - fromId: 2884fa72-0008-420a-b44b-0c393a70734a
        toId: f0a9e57e-756c-45cd-b7cb-ded10de9a0f1
      - fromId: 2884fa72-0008-420a-b44b-0c393a70734a
        toId: 1114ad29-7e4e-44d1-a813-88c7b3bc2dae
      - fromId: 1114ad29-7e4e-44d1-a813-88c7b3bc2dae
        toId: 75c880dd-c3cd-40a7-a7df-8a58324f6496
      - fromId: bf59301d-887c-42ad-97c1-746a7fb8bf2f
        toId: 75c880dd-c3cd-40a7-a7df-8a58324f6496
      - fromId: 2884fa72-0008-420a-b44b-0c393a70734a
        toId: 61a94fb6-1ff0-47ec-a600-5d8a8fcf25f1
      - fromId: 75c880dd-c3cd-40a7-a7df-8a58324f6496
        toId: f0a9e57e-756c-45cd-b7cb-ded10de9a0f1
  X:\coding\gamepad-cli-hub:
    dirPath: X:\coding\gamepad-cli-hub
    items:
      - id: 8810d3c5-c0ba-4f05-953f-2edf7cff8276
        dirPath: X:\coding\gamepad-cli-hub
        title: "New Planv32423423  "
        description: sdaf sd
        status: pending
        createdAt: 1776461352307
        updatedAt: 1776461369686
      - id: 43354400-40ab-461c-b22b-99100e0a70ba
        dirPath: X:\coding\gamepad-cli-hub
        title: New Planas
        description: asdasd
        status: startable
        createdAt: 1776461353602
        updatedAt: 1776461363934
    dependencies:
      - fromId: 43354400-40ab-461c-b22b-99100e0a70ba
        toId: 8810d3c5-c0ba-4f05-953f-2edf7cff8276
