tasks:
  - id: 85057220-da08-451f-ab93-818d4dbd9990
    title: Test
    planIds: []
    initialPrompt: Test
    cliType: claude-code
    scheduledTime: 2026-04-28T03:03:50.344Z
    dirPath: X:\\coding\\test
    status: executing
    createdAt: 1777345431344
    sessionId: pty-1777345431344
