tasks:
  - id: 030e054f-45c7-4887-a934-e35e7b6ddb8f
    title: Test
    planIds: []
    initialPrompt: Test
    cliType: claude-code
    scheduledTime: 2026-04-27T22:24:26.224Z
    dirPath: X:\\coding\\test
    status: executing
    createdAt: 1777328667224
    sessionId: pty-1777328667224
