cliTypes:
  claude-code:
    name: Claude Code
    command: claude
    initialPrompt: quack quack motehrfucker
  copilot-cli:
    name: GitHub Copilot CLI
    command: copilot
    initialPrompt: ""
  python:
    name: python
    command: python
    initialPrompt: ""
