cliTypes:
  claude-code:
    name: Claude Code
    terminal: wt
    command: claude
  copilot-cli:
    name: GitHub Copilot CLI
    terminal: wt
    command: copilot
  generic-terminal:
    name: Generic Terminal
    terminal: wt
    command: ""
  python:
    name: python
    terminal: wt
    command: python
